### PR TITLE
fix delete

### PR DESCRIPTION
**Pull request by QwertyQwh**
Fixed the delete URL as well as return code

### CODE REVIEW

**Comment by EyuEyu** [comment]
It seems that the case when the item is not in the database is not handled. Maybe you could just copy the code from the template and modify it.

**Comment by EyuEyu** [comment]
It seems that the case when the item is not in the database is not handled. Maybe you could just copy the code from the template and modify it.

**Comment by QwertyQwh** [comment]
In the comments he said we should always return 204 no matter what, right? As far as that goes, there's no need to check whether the promotion is in the database since the user will not need the feedback anyway. If the promotion doesn't exist, the operation just does nothing.

In my previous work, the convention was to return 404 when an item was not found, which is what I did. However, I don't think this is necessary by his convention.

**Comment by EyuEyu** [comment]
Thanks for the clarification. Then we may need to modify the comment of the method accordingly (deleting line 103 in routes.py).

**Pull request merged**
